/* ===== Train 23:59 · src/audio.js — صدا و موسیقی ===== */
var Au=(function(){var AC=null,M=null,mu=false,mBus=null,musOn=false,musOff=false,trackReady=false,trackOn=false,el=null,rumG=null;
 function dist(a){var n=1024,c=new Float32Array(n);for(var i=0;i<n;i++){var x=i*2/n-1;c[i]=(3+a)*x*20*Math.PI/180/(Math.PI+a*Math.abs(x));}return c;}
 function init(){if(AC)return;try{var C=window.AudioContext||window.webkitAudioContext;if(!C)return;AC=new C();var cp=AC.createDynamicsCompressor();cp.threshold.value=-12;cp.ratio.value=6;cp.connect(AC.destination);M=AC.createGain();M.gain.value=0;M.connect(cp);var dg=AC.createGain();dg.gain.value=.34;dg.connect(M);
  [55,55.7,82.5].forEach(function(f,i){var o=AC.createOscillator();o.type='sine';o.frequency.value=f;var g=AC.createGain();g.gain.value=i===2?.22:.44;o.connect(g);g.connect(dg);o.start();});
  var b=AC.createBuffer(1,AC.sampleRate*2,AC.sampleRate),ch=b.getChannelData(0);for(var i=0;i<ch.length;i++)ch[i]=Math.random()*2-1;var s=AC.createBufferSource();s.buffer=b;s.loop=true;var lp=AC.createBiquadFilter();lp.type='lowpass';lp.frequency.value=420;var ng=AC.createGain();ng.gain.value=.26;var lf=AC.createOscillator();lf.frequency.value=2.1;var lg=AC.createGain();lg.gain.value=.14;lf.connect(lg);lg.connect(ng.gain);lf.start();s.connect(lp);lp.connect(ng);ng.connect(M);s.start();
  var rum=AC.createOscillator();rum.type='sawtooth';rum.frequency.value=42;rumG=AC.createGain();rumG.gain.value=0;var rlp=AC.createBiquadFilter();rlp.type='lowpass';rlp.frequency.value=160;rum.connect(rlp);rlp.connect(rumG);rumG.connect(M);rum.start();
  M.gain.linearRampToValueAtTime(mu?0:.8,AC.currentTime+2);if(AC.state==='suspended')AC.resume();}catch(e){}}
 function tension(p){if(!AC||!rumG)return;try{rumG.gain.linearRampToValueAtTime(mu?0:clamp((p-30)/70,0,1)*0.18,AC.currentTime+.4);}catch(e){}}
 function tryTrack(){try{el=new Audio();el.src=A_MUSIC;el.loop=true;el.preload='auto';el.crossOrigin='anonymous';el.addEventListener('canplaythrough',function(){trackReady=true;});el.addEventListener('loadeddata',function(){trackReady=true;});}catch(e){}}
 function music(){if(!AC)return;if(!mBus){mBus=AC.createGain();mBus.gain.value=.16;mBus.connect(M);}if(musOn)return;if(trackReady&&el&&!trackOn){trackOn=true;try{var src=AC.createMediaElementSource(el);src.connect(M);el.play();if(musOff)el.muted=true;return;}catch(e){}}
  musOn=true;var pg=[[196,246.94,293.66],[174.61,220,261.63],[220,261.63,329.63],[146.83,196,246.94]];var i=0;
  function ch(){var ns=pg[i%pg.length];i++;var t0=AC.currentTime;for(var k=0;k<ns.length;k++){var o=AC.createOscillator();o.type='sine';o.frequency.value=ns[k];var g=AC.createGain();g.gain.setValueAtTime(.0001,t0);g.gain.linearRampToValueAtTime(.15,t0+2.6);g.gain.linearRampToValueAtTime(.0001,t0+9);o.connect(g);g.connect(mBus);o.start(t0);o.stop(t0+9.3);}}
  ch();setInterval(ch,9000);}
 function toggleMusic(){musOff=!musOff;if(el)el.muted=musOff;else if(mBus)mBus.gain.value=musOff?0:.16;return musOff;}
 function beep(fr,d,vv,t){if(!AC||mu)return;var tm=AC.currentTime;fr.forEach(function(f){var o=AC.createOscillator();o.type=t||'sawtooth';o.frequency.value=f;var g=AC.createGain();g.gain.setValueAtTime(0,tm);g.gain.linearRampToValueAtTime(vv,tm+.03);g.gain.exponentialRampToValueAtTime(.0001,tm+d);o.connect(g);g.connect(M);o.start(tm);o.stop(tm+d+.05);});}
 function horn(){if(!AC||mu)return;var tm=AC.currentTime,e=AC.createGain();e.gain.setValueAtTime(.0001,tm);e.gain.linearRampToValueAtTime(.42,tm+.05);e.gain.linearRampToValueAtTime(.3,tm+.9);e.gain.linearRampToValueAtTime(.0001,tm+1.5);e.connect(M);[220,277,330].forEach(function(f,i){var o=AC.createOscillator();o.type='sawtooth';o.frequency.value=f;var sh=AC.createWaveShaper();sh.curve=dist(6);var g=AC.createGain();g.gain.value=.18;o.connect(sh);sh.connect(g);g.connect(e);o.start(tm);o.stop(tm+1.5);});}
 tryTrack();
 return{init:init,music:music,horn:horn,tension:tension,brake:function(){beep([150,186],.5,.3,'triangle');},click:function(){beep([520],.09,.22,'triangle');},bad:function(){beep([110,146],.4,.3,'sawtooth');},good:function(){beep([523,659,784],.25,.22,'triangle');},toggle:function(){mu=!mu;if(M&&AC)M.gain.linearRampToValueAtTime(mu?0:.8,AC.currentTime+.3);return mu;},toggleMusic:toggleMusic,musicOff:function(){return musOff;},muted:function(){return mu;}};})();