/* ===== Train 23:59 · src/ui.js — داده، حبابِ راهنما، رابط ===== */
var DATA=null,UIo={},RS=[],CL={},LO=[],PO=[],SK={},UG=[],AR=[],SN=[],EVo=[],GD=[];
function bind(){if(!DATA)return;UIo=DATA.ui||{};RS=DATA.res||[];CL=DATA.clues||{};LO=DATA.loc||[];PO=DATA.pool||[];SK=DATA.skill||{};UG=DATA.upg||[];AR=DATA.arch||[];SN=DATA.sn||[];EVo=DATA.ev||[];GD=DATA.guide||[];}
function S(k){return SL(UIo[k]!=null?UIo[k]:k);}
var UNL={};try{UNL=JSON.parse(localStorage.getItem('t59ach')||'{}')||{};}catch(e){UNL={};}
function saveAch(){try{localStorage.setItem('t59ach',JSON.stringify(UNL));}catch(e){}}
var AQ=[],ALQbusy=false,ALsig={};
function alertCheck(s){if(!s||typeof ALERTS==='undefined')return;var now=Date.now();
 function ch(k,low,rec){if(!low){if(rec)ALsig[k]=0;return;}if(ALsig[k]&&now-ALsig[k]<30000)return;ALsig[k]=now;AQ.push(k);if(!ALQbusy)pumpQ();}
 ch('food',s.food<25,s.food>38);ch('fuel',s.fuel<14,s.fuel>24);ch('sanity',s.sanity<32,s.sanity>45);ch('time',s.time<20,false);ch('pur',s.pur>70,s.pur<55);}
function pumpQ(){var el=document.getElementById('alert');if(!el){AQ=[];ALQbusy=false;return;}if(!AQ.length){ALQbusy=false;el.classList.add('hidden');return;}ALQbusy=true;var k=AQ.shift();var a=ALERTS[k];if(!a){pumpQ();return;}el.style.borderInlineStartColor=a.c;el.innerHTML='<div class="ai">'+ic(a.i,'',a.c)+'</div><div class="ab"><b>'+SL(a.t)+'</b><span>'+SL(a.m)+'</span></div>';el.classList.remove('hidden');void el.offsetWidth;el.classList.add('on');setTimeout(function(){el.classList.remove('on');setTimeout(pumpQ,450);},4200);}
var NPC=NPCDEF,GF={},BQ=[],bTimer=null;
function npcBind(){NPC=(DATA&&DATA.npc&&DATA.npc.lines)?DATA.npc:NPCDEF;GF={};}
function nMatch(w){if(!w)return true;var s=G.S();
 if(w.foodLt!=null&&!(s.food<w.foodLt))return false;if(w.fuelLt!=null&&!(s.fuel<w.fuelLt))return false;if(w.sanityLt!=null&&!(s.sanity<w.sanityLt))return false;
 if(w.purGt!=null&&!(s.pur>w.purGt))return false;if(w.st!=null&&s.st!==w.st)return false;if(w.stGte!=null&&!(s.st>=w.stGte))return false;
 if(w.timeLt!=null&&!(s.time<w.timeLt))return false;if(w.clueGte!=null&&!(s.clues.length>=w.clueGte))return false;
 if(w.paxMoodLt!=null&&!s.pax.some(function(p){return (p.md==null?100:p.md)<w.paxMoodLt;}))return false;if(w.flag&&!GF[w.flag])return false;if(w.notFlag&&GF[w.notFlag])return false;return true;}
function nSay(t){if(!t)return;BQ.push(t);if(BQ.length===1)nShow();}
function nShow(){var el=document.getElementById('bubble');var full=BQ[0],i=0;el.classList.remove('hidden');el.innerHTML='<span class="who">'+SL(NPC.name)+'</span><span class="tx"></span>';var tx=el.querySelector('.tx');if(bTimer)clearInterval(bTimer);bTimer=setInterval(function(){i++;tx.textContent=full.slice(0,i);if(i>=full.length){clearInterval(bTimer);bTimer=null;}},20);}
function nAdv(){var el=document.getElementById('bubble');if(bTimer){clearInterval(bTimer);bTimer=null;el.querySelector('.tx').textContent=BQ[0];return;}BQ.shift();if(BQ.length)nShow();else el.classList.add('hidden');}
function nCheck(){if(!FIRST)return;if(!NPC.lines||!NPC.lines.length)return;if(UI.busy())return;if(!document.getElementById('bubble').classList.contains('hidden'))return;var s=G.S();if(GF.st===s.st)return;var best=null;
 NPC.lines.forEach(function(l){if(l.once!==false&&GF['n_'+l.id])return;if(l.cd&&l.cdKey&&GF['c_'+l.cdKey]!=null&&(s.st-GF['c_'+l.cdKey])<l.cd)return;if(!nMatch(l.when))return;if(!best||(l.p||0)>(best.p||0))best=l;});
 if(best){GF['n_'+best.id]=1;if(best.cdKey)GF['c_'+best.cdKey]=s.st;GF.st=s.st;nSay(SL(best.t));}}
var UI=(function(){var pan=document.getElementById('panel'),tn=document.getElementById('tnote'),u={m:'main',txt:'',ev:null,kind:'main',loc:0},ty=null;
 function res(){var s=G.S();if(!s)return;var el=document.getElementById('res');el.innerHTML='';(RS||[]).forEach(function(r){var v=Math.round(s[r.k]),cr=v<=r.cr,d=document.createElement('div');d.className='chip'+(cr?' crit':'');d.innerHTML='<div class="top">'+ic(r.k,'s',r.c)+'<span class="val">'+N(v)+'</span></div><div class="lbl">'+SL(r.l)+'</div><div class="bar"><div class="fill" style="width:'+v+'%;background:'+r.c+'"></div></div>';el.appendChild(d);});
  document.getElementById('scrapIc').innerHTML=ic('scrap','s','#d0d7e6');document.getElementById('scrapVal').textContent=N(s.scrap);document.getElementById('progFill').style.width=Math.round((s.st-1)/s.tot*100)+'%';document.getElementById('purFill').style.width=Math.min(100,s.pur)+'%';document.getElementById('stnNow').textContent=N(s.st);document.getElementById('stnTot').textContent=N(s.tot);document.getElementById('clock').textContent=clk(timeClock(s.time));
  var px=document.getElementById('pax');px.innerHTML='';s.pax.forEach(function(p){var sp=document.createElement('span');sp.innerHTML=ic(skIc(p.sk),'','#c9b98a');sp.title=SL(p.nm)+' · '+(p.md==null?100:Math.round(p.md))+'%';px.appendChild(sp);});document.getElementById('mute').innerHTML=ic(Au.muted()?'muted':'sound','s');document.getElementById('musicBtn').innerHTML=ic(Au.musicOff()?'musicOff':'music','s');
  alertCheck(s);}
 function tI(el,txt,done){el.textContent='';if(!txt){if(done)done();return;}ty={el:el,t:txt,i:0,d:done};}
 function tick(dt){if(!ty)return;ty.i+=dt*55;var k=Math.floor(ty.i);if(k>=ty.t.length){ty.el.textContent=ty.t;var d=ty.d;ty=null;if(d)d();return;}ty.el.textContent=ty.t.slice(0,k);}
 function fin(){if(ty){ty.el.textContent=ty.t;var d=ty.d;ty=null;if(d)d();}}
 function set(h){pan.innerHTML=h;}
 function render(){var s=G.S();
  if(u.m==='main'){var lf=s.loc.filter(function(l){return !l.used;}).length;set('<div class="ptitle">'+ic('train','','#ffd76a')+' '+S('station')+' <b>'+N(s.st)+'</b> · <span>'+SL(SN[(s.st-1)%SN.length]||'')+'</span> · '+Stn.an()+'</div><div class="pdesc" id="desc"></div><div class="grid">'+
    '<button class="choice" data-a="explore">'+ic('explore')+' '+S('explore')+(lf?' ('+N(lf)+')':'')+'</button><button class="choice" data-a="shop">'+ic('shop')+' '+S('market')+'</button><button class="choice" data-a="pax">'+ic('people')+' '+S('pax')+' ('+N(s.pax.length)+')</button><button class="choice" data-a="upg">'+ic('upgrade')+' '+S('upgrade')+'</button>'+
    '<button class="choice" data-a="rest">'+ic('rest')+' '+S('rest')+'<span class="sub">'+S('restS')+'</span></button><button class="choice" data-a="journal">'+ic('journal')+' '+S('journalB')+' ('+N(s.clues.length)+'/'+N(6)+')</button></div><div class="grid wide"><button class="choice gold" data-a="depart">'+ic('train')+' '+S('depart')+'</button></div><div class="grid"><button class="choice" data-a="help" style="padding:8px">'+ic('help')+' '+S('help')+'</button><button class="choice" data-a="ach" style="padding:8px">'+ic('trophy')+' '+S('ach')+'</button></div><div class="pnote">'+S('acts')+': '+N(Math.floor(s.time/ACT))+' · '+S('pur')+': '+N(Math.round(s.pur))+'%</div>');
   var d=document.getElementById('desc');if(u.txt){d.textContent=u.txt;u.txt='';}else tI(d,S('mainD').replace('{a}',Stn.an()));}
  else if(u.m==='explore'){var cd='';s.loc.forEach(function(l,i){var df=Stn.def(l.id);cd+='<button class="choice'+(l.used?' dim':'')+'" data-a="loc" data-b="'+i+'">'+ic('explore')+' '+SL(df.nm)+'<span class="sub">'+(l.used?S('done'):S('oneA'))+'</span></button>';});set('<div class="ptitle">'+ic('explore','','#ffd76a')+' '+S('explT')+'</div><div class="pdesc">'+S('explS')+'<br>'+SL('هر کاوش ریسک دارد؛ همیشه گنج نیست.|Every search is risky.')+'</div><div class="grid">'+cd+'</div><div class="grid wide"><button class="choice" data-a="back">'+S('back')+'</button></div>');}
  else if(u.m==='depth'){var df=Stn.def(s.loc[u.loc]?s.loc[u.loc].id:'');set('<div class="ptitle">'+ic('explore','','#ffd76a')+' '+SL(df.nm)+'</div><div class="pdesc">'+SL('چقدر عمیق بگردی؟|How deep will you search?')+'</div><div class="grid wide">'+
    '<button class="choice" data-a="deep" data-b="1">'+SL('سطحی (۲ زمان)|Shallow (2 time)')+'<span class="sub">'+SL('امن؛ پاداشِ کم|Safe; small reward')+'</span></button>'+
    '<button class="choice" data-a="deep" data-b="2">'+SL('متوسط (۴ زمان)|Medium (4 time)')+'<span class="sub">'+SL('۳۰٪ خطر|30% risk')+'</span></button>'+
    '<button class="choice" data-a="deep" data-b="3">'+SL('عمیق (۸ زمان)|Deep (8 time)')+'<span class="sub">'+SL('۵۵٪ خطر؛ شانسِ سرنخ|55% risk; clue chance')+'</span></button>'+
    '</div><div class="grid wide"><button class="choice" data-a="expbk">'+S('back')+'</button></div>');}
  else if(u.m==='result'){set('<div class="ptitle">'+S('result')+'</div><div class="pdesc" id="desc"></div><div class="grid wide"><button class="choice gold" data-a="back">'+S('cont')+'</button></div>');tI(document.getElementById('desc'),u.txt);}
  else if(u.m==='shop'){var sh=s.shop;function row(lb,k,ico,unit){var q=sh[k];if(!q)return'';if(q.st<=0)return'<button class="choice dim">'+ic(ico)+' '+lb+' — '+S('noStock')+'</button>';return'<button class="choice" data-a="buy" data-b="'+k+'">'+ic(ico)+' '+lb+' ×'+N(unit)+'<span class="sub">'+N(q.pr*unit)+' '+S('scrap')+' · '+S('stock')+' '+N(q.st)+'</span></button>';}set('<div class="ptitle">'+ic('shop','','#ffd76a')+' '+S('shopT')+' · '+Stn.an()+'</div><div class="pdesc">'+S('shopS')+'</div><div class="grid">'+row(S('food'),'food','food',5)+row(S('fuel'),'fuel','fuel',5)+'<button class="choice" data-a="buy" data-b="medkit">'+ic('cross')+' '+S('medkit')+'<span class="sub">'+N(sh.medkit.pr)+' '+S('scrap')+'</span></button><button class="choice" data-a="buy" data-b="alcohol">'+ic('sanity')+' '+S('alcohol')+'<span class="sub">'+N(sh.alcohol.pr)+' '+S('scrap')+'</span></button>'+(sh.map.st>0?'<button class="choice" data-a="buy" data-b="map">'+ic('journal')+' '+S('map')+'<span class="sub">'+N(sh.map.pr)+' '+S('mapS')+'</span></button>':'')+'</div><div class="grid wide"><button class="choice" data-a="back">'+S('back')+'</button></div><div class="pnote">'+S('have')+N(s.scrap)+'</div>');}
  else if(u.m==='pax'){var rs='';if(!s.pax.length)rs='<div class="pdesc">'+S('noPax')+'</div>';if(u.ptxt)rs='<div class="pdesc">'+u.ptxt+'</div>'+rs;s.pax.forEach(function(p,i){var md=p.md==null?100:p.md;rs+='<button class="choice" data-a="talk" data-b="'+i+'">'+ic(skIc(p.sk),'','#c9b98a')+' '+SL(p.nm)+' — '+SL(p.ro)+'<span class="sub">'+SL('حال|mood')+' '+N(Math.round(md))+'% · '+SL('وفاداری|loyalty')+' '+N(p.ly)+'%</span></button>';});set('<div class="ptitle">'+ic('people','','#ffd76a')+' '+S('paxT')+'</div>'+rs+'<div class="grid wide"><button class="choice" data-a="back">'+S('back')+'</button></div><div class="pnote">'+SL('گفت‌وگو = ۴ زمان؛ حال را برمی‌گرداند.|Talk = 4 time; restores mood.')+'</div>');}
  else if(u.m==='upg'){var ur='';(UG||[]).forEach(function(q){var lv=G.upg(q.id),co=Math.round(q.co*(1+lv*.7)),can=s.scrap>=co;ur+='<button class="choice'+(can?'':' dim')+'" data-a="upgItem" data-b="'+q.id+'">'+ic(q.ic)+' '+SL(q.nm)+' ('+S('lvl')+' '+N(lv)+')<span class="sub">'+SL(q.d)+' · '+N(co)+' '+S('scrap')+'</span></button>';});set('<div class="ptitle">'+ic('upgrade','','#ffd76a')+' '+S('upgT')+' · '+S('lvl')+' '+N(G.lvl())+'</div>'+ur+'<div class="grid wide"><button class="choice" data-a="back">'+S('back')+'</button></div><div class="pnote">'+S('have')+N(s.scrap)+'</div>');}
  else if(u.m==='route'){set('<div class="ptitle">'+ic('train','','#ffd76a')+' '+S('routeT')+'</div><div class="pdesc">'+S('routeS')+'</div><div class="grid wide"><button class="choice" data-a="go" data-b="fast">'+ic('bolt')+' '+S('fast')+'<span class="sub">'+S('fastS')+'</span></button><button class="choice" data-a="go" data-b="norm">'+ic('arrow')+' '+S('norm')+'<span class="sub">'+S('normS')+'</span></button><button class="choice" data-a="go" data-b="stealth">'+ic('cloud')+' '+S('stealth')+'<span class="sub">'+S('stealthS')+'</span></button></div>');}
  else if(u.m==='event'){var e=u.ev,cs='';if(e)e.ch.forEach(function(c,i){cs+='<button class="choice" data-a="evch" data-b="'+i+'">'+SL(c.t)+'</button>';});set('<div class="ptitle">'+ic('alert','','#ff9d3c')+' '+S('event')+'</div><div class="pdesc" id="desc"></div><div class="grid wide">'+cs+'</div>');tI(document.getElementById('desc'),e?SL(e.t):'');}
  else if(u.m==='npc'){var isR=u.kind==='ret';set('<div class="ptitle">'+ic('person','',isR?'#ff9d3c':'#ffd76a')+' '+(isR?SL('برگشت|Returned'):S('npcT'))+'</div><div class="pdesc" id="desc"></div><div class="grid wide"><button class="choice gold" data-a="recruit">'+(isR?SL('نجاتش بده|Save them'):S('board'))+'<span class="sub">'+SL('۶ غذا · ۴ زمان|6 food · 4 time')+'</span></button><button class="choice" data-a="refuse">'+(isR?SL('باز هم رهایش کن|Abandon'):S('pass'))+'<span class="sub">'+(isR?SL('۱۴− سلامت|−14 health'):SL('۸− سلامت|−8 health'))+'</span></button></div>');tI(document.getElementById('desc'),u.txt);}}
 function show(m){u.m=m;pan.classList.remove('hidden');render();}
 return{res:res,render:render,show:show,setText:function(v){u.txt=v;},setPax:function(v){u.ptxt=v;},setEv:function(e){u.ev=e;},getEv:function(){return u.ev;},getM:function(){return u.m;},setLoc:function(i){u.loc=i;},getLoc:function(){return u.loc;},setKind:function(k){u.kind=k;},getKind:function(){return u.kind;},tick:tick,hide:function(){pan.classList.add('hidden');},note:function(on,t){if(t)tn.textContent=t;tn.classList.toggle('on',!!on);},fin:fin,busy:function(){return !!ty;},bind:function(h){pan.addEventListener('click',function(e){var b=e.target.closest('[data-a]');if(!b)return;fin();Au.click();h(b.getAttribute('data-a'),b.getAttribute('data-b'));});}};})();